server:
  port: 8080
  servlet:
    context-path: /jokefeeder/api


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

feed:
  jokes:
    url: https://official-joke-api.appspot.com/jokes/random